### ISSUE TITLE
Why there is no cursor?

### ISSUE THREAD

**Issue by Mo7mud** [poovamraj/PinEditTextField#4]
It's very confusing to users not to see a cursor to indicate where they are writing.

I myself tapped on the edit text many times waiting for a cursor to show so I can start typing.

Is it possible to add one?

**Comment by poovamraj** [comment]
Hi, currently it is not supported because most of the Pin Field UI doesn't involve a cursor. The Pin Field will highlight (you can set this using highlight color) once it is focused and will dim down when it is not focused.

I will take this as a request, work on it, and release a new version.

Since the weekend is over here, I'll work on this request next weekend.

Thank you for the support!

**Comment by poovamraj** [comment]
Hi, 

I have completed your requests for the cursor. Please use the latest version

implementation 'com.poovam:pin-edittext-field:1.0.5'

Use the below line to enable the cursor
app:isCursorEnabled="true"


Find the samples below

![screenshot_1534351971](https://user-images.githubusercontent.com/15910425/44161211-45d98c80-a0da-11e8-9c8e-e9268ea20ef4.png)
![screenshot_1534351987](https://user-images.githubusercontent.com/15910425/44161212-45d98c80-a0da-11e8-9334-c447d394d062.png)
